@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

entity Money << record >> {
  - value: Double
  - unit: String
}
entity Operator << record >> {
  - id: Long
  - name: String
}
class Order {
  - price: Money
  - operator: Operator
  - typeItems: List<TypeItem>
  - term: Term
  - phoneNumber: String
  - fullName: String
}
entity OrderIDAndOddMany << record >> {
  - orderID: long
  - oddMoney: Money
}
entity OrderList << record >> {
  - connectionToDataBase: Connection
}
entity OrderViewAndTypesViews << record >> {
  - orderView: OrderView
  - typeViews: List<TypeView>
}
entity PickUpStation << record >> {
  - connectionToDataBase: Connection
  - address: String
}
class Register {
  - order: Order
  - ticketList: TicketList
  - orderList: OrderList
  - pickUpStation: PickUpStation
  - typeList: TypeList
}
entity Term << record >> {
  - value: Integer
}
class Ticket {
  - id: long
  - orderId: long
  - isReady: boolean
  - fullName: String
  - phoneNumber: String
  - isDone: boolean
  - name: String
}
entity TicketList << record >> {
  - connectionToDataBase: Connection
}
entity Type << record >> {
  - id: Long
  - term: Term
  - name: String
  - money: Money
  - create_time: LocalDateTime
  - info: String
}
entity TypeItem << record >> {
  - type: Type
  - count: int
}
class TypeList {
  - connectionToDataBase: Connection
}

Order                   -[#595959,dashed]->  Money                  
Order                   -[#595959,dashed]->  Operator               
Order                   -[#595959,dashed]->  OrderIDAndOddMany      
Order                   -[#595959,dashed]->  PickUpStation          
Order                   -[#595959,dashed]->  Term                   
Order                   -[#595959,dashed]->  TicketList             
Order                   -[#595959,dashed]->  Type                   
Order                   -[#595959,dashed]->  TypeItem               
Order                   -[#595959,dashed]->  TypeList               
OrderIDAndOddMany       -[#595959,dashed]->  Money                  
OrderList               -[#595959,dashed]->  Money                  
OrderList               -[#595959,dashed]->  OrderViewAndTypesViews 
OrderList               -[#595959,dashed]->  Term                   
OrderList               -[#595959,dashed]->  Type                   
OrderList               -[#595959,dashed]->  TypeItem               
PickUpStation           -[#595959,dashed]->  Money                  
PickUpStation           -[#595959,dashed]->  Operator               
PickUpStation           -[#595959,dashed]->  Order                  
PickUpStation           -[#595959,dashed]->  OrderIDAndOddMany      
PickUpStation           -[#595959,dashed]->  Term                   
PickUpStation           -[#595959,dashed]->  Type                   
PickUpStation           -[#595959,dashed]->  TypeItem               
Register                -[#595959,dashed]->  Money                  
Register                -[#595959,dashed]->  Order                  
Register                -[#595959,dashed]->  OrderList              
Register                -[#595959,dashed]->  OrderViewAndTypesViews 
Register                -[#595959,dashed]->  PickUpStation          
Register                -[#595959,dashed]->  Term                   
Register                -[#595959,dashed]->  Ticket                 
Register                -[#595959,dashed]->  TicketList             
Register                -[#595959,dashed]->  Type                   
Register                -[#595959,dashed]->  TypeItem               
Register                -[#595959,dashed]->  TypeList               
TicketList              -[#595959,dashed]->  Ticket                 
Type                    -[#595959,dashed]->  Money                  
Type                    -[#595959,dashed]->  Term                   
TypeItem                -[#595959,dashed]->  Money                  
TypeItem                -[#595959,dashed]->  Term                   
TypeItem                -[#595959,dashed]->  Type                   
TypeList                -[#595959,dashed]->  Money                  
TypeList                -[#595959,dashed]->  Term                   
TypeList                -[#595959,dashed]->  Type                   
@enduml
