@startuml
'https://plantuml.com/sequence-diagram

actor Касир

Касир -> ":System": newOrder()
Касир -> ":System": addType(name, count)
Касир <-- ":System": Всі додані типи
Касир -> ":System": getTerm()
Касир <-- ":System": Загальний термін вироблення
Касир -> ":System": getPrice()
Касир <-- ":System": Загальна ціна
Касир -> ":System": makePayment(countPayMoney, fullName, phoneNumber)
Касир <-- ":System": Решта, яку потрібно заплатити клієнтом
Касир -> ":System": getTypes(likeNameTypes)
Касир <-- ":System": Множину можливих типів для обрання
Касир -> ":System": getOrderTypes()
Касир <-- ":System": Всі додані типи
Касир -> ":System": getAllTickets()
Касир <-- ":System": Стан замовлень, які зафіксовані, але \nстворюються або ще не забрали
@enduml