@startuml



'nodes 
card Controller

card Register

card TypeList

'edges    
Controller -> Register: getTypes(likeNameTypes)
note top on link: За шаблоном Controller
Register -> TypeList: 1:types:=List<Type> getTypes(likeNameTypes)
note top on link: За шаблоном Information Experts
    

@enduml