@startuml


card Controller

card "order:Order" as Order

card ":Register" as Register

card "typeList:TypeList" as TypeList

card "typeItems:TypeItem" as TypeItem

Controller -> Register: typesItems:=addType(name, count) >
note top on link: За шаблоном Controller
Order --> TypeItem: 1.2:add(new TypeItem(type, count)) >
Order --> TypeList: 1.1:type:=getType(name) >
note bottom on link: За шаблоном Information Experts
Register -> Order: 1:addType(name, typeList, count) ►\n2:typesItems:=getTypeItems() >

@enduml